export const ADD_PROJECT = 'ADD_PROJECT';

export const SELECT_OPTION = 'SELECT_OPTION';
export const SELECT_PROJECT = 'SELECT_PROJECT';
export const CHANGE_CATEGORY = 'CHANGE_CATEGORY';

export const UPDATE_COSTS = 'UPDATE_COSTS';

export const OPEN_MODAL = 'OPEN_MODAL';
export const CLOSE_MODAL = 'CLOSE_MODAL';
